kind: pipeline
type: docker
name: deploy-bot

steps:
  - name: build
    image: docker:20.10
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t telegram-bot:latest .

  - name: deploy
    image: docker:20.10
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker stop telegram-bot || true
      - docker rm telegram-bot || true
      - docker run -d --name telegram-bot telegram-bot:latest

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
