kind: pipeline
type: docker
name: deploy-bot

steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 185.80.129.200
      username: root
      password:
        from_secret: ssh_password
      script:
        - cd /opt/bot/telegram-bot || mkdir -p /opt/bot/telegram-bot && cd /opt/bot/telegram-bot
        # забираем свежий код из репозитория
        - if [ ! -d ".git" ]; then git clone https://github.com/imushroom32/Lottery.git .; else git pull; fi
        # билдим и деплоим контейнер
        - docker build -t telegram-bot:latest .
        - docker stop telegram-bot || true
        - docker rm telegram-bot || true
        - docker run -d --name telegram-bot -e BOT_TOKEN=$BOT_TOKEN -e GROUP_CHAT_ID=$GROUP_CHAT_ID -e ADMIN_IDS=$ADMIN_IDS -v /opt/drone/data:/opt/drone/data telegram-bot:latest
