kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: docker:20.10
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t telegram-bot:latest .

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
