kind: pipeline
type: docker
name: deploy-bot

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: your-dockerhub-user/telegram-bot
      tags: latest
      dry_run: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 185.80.129.200
      username: root
      password:
        from_secret: ssh_password
      script:
        - docker pull your-dockerhub-user/telegram-bot:latest
        - docker stop telegram-bot || true
        - docker rm telegram-bot || true
        - docker run -d --name telegram-bot -e BOT_TOKEN=$BOT_TOKEN -e GROUP_CHAT_ID=$GROUP_CHAT_ID -e ADMIN_IDS=$ADMIN_IDS -v /opt/drone/data:/opt/drone/data your-dockerhub-user/telegram-bot:latest
